# Generated by Django 5.0.6 on 2024-09-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(related_name="product", to="app.category"),
        ),
    ]
